apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: planning-poker
servers: 1
agents: 2
image: rancher/k3s:v1.28.5-k3s1
ports:
  - port: 3000:80
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  create:
    name: planning-poker-registry
    host: "0.0.0.0"
    hostPort: "5000"
