apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "planning-poker.fullname" . }}-ui
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      {{- include "planning-poker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "planning-poker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      serviceAccountName: {{ include "planning-poker.serviceAccountName" . }}
      containers:
      - name: ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
        {{- range .Values.ui.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
