apiVersion: v1
kind: Service
metadata:
  name: {{ include "planning-poker.fullname" . }}-ui
  labels:
    {{- include "planning-poker.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.ui.service.type "NodePort") .Values.ui.service.nodePort }}
    nodePort: {{ .Values.ui.service.nodePort }}
    {{- end }}
  selector:
    {{- include "planning-poker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
