apiVersion: v2
name: planning-poker
description: A Helm chart for Planning Poker application
type: application
version: 1.0.1
appVersion: "1.0.1"
keywords:
  - planning-poker
  - agile
  - estimation
maintainers:
  - name: Planning Poker Team
